config/routes.rb
Rails.application.routes.draw do
    	

   	root to: "home#index"
  
	get 'user/dash'

	devise_for :users
	get 'home/index'

	get 'dash' => "user#dash"

	devise_scope :user do
		get "user_signup", to: "devise/registrations#new"
		get "user_login", to: "devise/sessions#new"
		get "user_logout", to: "devise/sessions#destroy"
	end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

before_action :authenticate_user!

  def dash
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rails_helper.rb
module RailsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
  <script type="text/javascript"> window.location.href="/dash"</script>
<% end %>




<body id="page-top">
    <!-- Navigation -->
    <a class="menu-toggle rounded" href="#">
      <i class="fa fa-bars"></i>
    </a>
    <nav id="sidebar-wrapper">
      <ul class="sidebar-nav">
        <li class="sidebar-brand">
          <a class="js-scroll-trigger" href="#page-top">Start Bootstrap</a>
        </li>
        <li class="sidebar-nav-item">
          <a class="js-scroll-trigger" href="#page-top">Home</a>
        </li>
        <li class="sidebar-nav-item">
          <a class="js-scroll-trigger" href="#about">About</a>
        </li>
        <li class="sidebar-nav-item">
          <a class="js-scroll-trigger" href="#services">Services</a>
        </li>
        <li class="sidebar-nav-item">
          <a class="js-scroll-trigger" href="#portfolio">Portfolio</a>
        </li>
        <li class="sidebar-nav-item">
          <a class="js-scroll-trigger" href="#contact">Contact</a>
        </li>
      </ul>
    </nav>

    <!-- Header -->
    <header class="masthead d-flex">
      <div class="container text-center my-auto">
        
        <h1 class="mb-1">It's time you made the right trades.</h1>
        <br>
        <h4 class="mb-5">Sign up today and know what coins have potential to go big.<br>

        </h4>

        <%= link_to "Sign Up", user_signup_path, class:"btn btn-success btn-lg js-scroll-trigger" %>


        <a class="btn btn-primary btn-lg js-scroll-trigger" href="#about">Learn More</a>

      </div>
      <div class="overlay"></div>
    </header>

    <!-- About -->
    <section class="content-section bg-light" id="about">
      <div class="container text-center">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h2>We do the research. You get best trades.</h2>
            <p class="lead mb-5"> Our team of cryptocurrency analysts look through hundreds of coins, ICOs, and technology to find the best and most promising investments. With 30 new ICOs launching each day, our team is hard at work sifting through the dirt to find the gold. Each week we'll post a new and promising technology with a high posibility of return on your investment.</p>
          </div>

          <div class="col-lg-10 mx-auto">
            <h2>What's the catch?</h2>
            <p class="lead mb-5">Good news, there isn't any! The Coin To Buy team is a group of blockchain and cryptocurrency enthusisests and investors who not only want to make money (which we love doing...), but seek to support this new technology that will and is changing the world. Our mission is to make known the real inovators and problem solvers in blockchain technology. Why not share the knowledge and findings so everyone can benefit? All you need to do sign up and you'll be ready to go.</p>
          </div>

        </div>
      </div>
    </section>

    <!-- Services -->
    <section class="content-section bg-primary text-white text-center" id="services">
      <div class="container">
        <div class="content-section-heading">
          <h2 class="mb-5">How to get started?</h2>
        </div>
        <div class="row">
          <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
            <span class="service-icon rounded-circle mx-auto mb-3">
              <i class="fa fa-user-plus" aria-hidden="true"></i>
            </span>
            <h4>
              <strong>1. Sign Up</strong>
            </h4>
            <p class="text-faded mb-0">Join our site for free.</p>
          </div>
          <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
            <span class="service-icon rounded-circle mx-auto mb-3">
              <i class="fa fa-exchange" aria-hidden="true"></i>
            </span>
            <h4>
              <strong>2. Join an exchange</strong>
            </h4>
            <p class="text-faded mb-0">To buy coins we recommend you sign up for Binance or Bittrex.</p>
          </div>
          <div class="col-lg-3 col-md-6 mb-5 mb-md-0">
            <span class="service-icon rounded-circle mx-auto mb-3">
              <i class="fa fa-btc" aria-hidden="true"></i>
            </span>
            <h4>
              <strong>3. Buy some coins</strong>
            </h4>
            <p class="text-faded mb-0">Tip: Only invest what you're prepared to lose. So don't sell your house.</p>
          </div>
          <div class="col-lg-3 col-md-6">
            <span class="service-icon rounded-circle mx-auto mb-3">
              <i class="fa fa-usd" aria-hidden="true"></i>
            </span>
            <h4>
              <strong>4. Make money!</strong>
            </h4>
            <p class="text-faded mb-0">HODL or sell whenever you feel like it.</p>
          </div>
        </div>
      </div>
    </section>
       

    <!-- Call to Action -->
    <section class="content-section bg-primary text-white calltoactionsec">
      <div class="container text-center ">
        <h2 class="mb-4">Get Started!</h2>
        <a href="#" class="btn btn-success btn-lg btn-light mr-4">Sign Up!</a>
      </div>
    </section>


    <!-- Footer -->
    <footer class="footer text-center">
      <div class="container">
        <p class="text-muted small mb-0">Copyright &copy; Your Website 2017</p>
      </div>
    </footer>

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded js-scroll-trigger" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="js/stylish-portfolio.min.js"></script>

  </body>

</html>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" id="mainNav" style="background-color: #2d2d2d;">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" style="color: #ff6c00; font-weight: 800;">CoinToBuyToday</a>

    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav text-uppercase ml-auto">

        <% if user_signed_in? %>
        <%= link_to "Log Out", user_logout_path, class:"nav-item nav-link js-scroll-trigger"%>
        <% else %>
        <%= link_to "Sign In", user_login_path, class:"nav-item nav-link js-scroll-trigger"%>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

<span id="notice"><%= notice %></span>  
<span id="alert"><%= alert %></span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coinstobuy</title>
    <%= csrf_meta_tags %>


    <!-- Custom CSS -->
   

    <link href="app/assets/stylesheets/stylish-portfolio.css" rel="stylesheet">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Custom Fonts -->

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <link href="vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">
  

  </head>

   

  <body>

    <%= render 'layouts/header' %>

    <%= yield %>

  </body>
</html>

app/views/rails/User.html.erb
<h1>Rails#User</h1>
<p>Find me in app/views/rails/User.html.erb</p>

app/views/rails/controller.html.erb
<h1>Rails#controller</h1>
<p>Find me in app/views/rails/controller.html.erb</p>

app/views/rails/g.html.erb
<h1>Rails#g</h1>
<p>Find me in app/views/rails/g.html.erb</p>

app/views/rails/index.html.erb
<h1>Rails#index</h1>
<p>Find me in app/views/rails/index.html.erb</p>

app/views/user/dash.html.erb
<section class="content-section bg-light" id="about">
  <div class="container text-center">
    <div class="row">
      <div class="col-lg-10 mx-auto">
        <h1>Top coin this week is:</h1>
        <div id="coin-display">$CFD</div>
      </div>
    </div>
    <br>
    <%= link_to "Market Data", user_logout_path, class:"btn btn-success btn-lg marketdatabtn"%>
    <%= link_to "Buy/Sell", user_logout_path, class:"btn btn-primary btn-lg marketdatebtn"%>

  </div>
</section>

<section class="content-section" id="coin-info-wrapper">

<div class="container text-center">
    <div class="row">
      <div class="col-lg-10 mx-auto coin-info">
        <h2>Why $CFD?</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rutrum quam vitae metus suscipit porta. Donec elementum lacus vel varius cursus. Nullam a mauris efficitur, aliquam felis at, hendrerit ligula. Aenean sodales, urna id porttitor tempor, metus mi fermentum sem, id vehicula turpis nibh eu dui. Integer eu tristique nisi. Proin quis consequat nunc, vestibulum placerat ante. Nullam posuere fringilla arcu, a imperdiet nisl bibendum a.</p>
      </div>
    </div>
    <br>

</div>


  <div class="container text-center">
    <div class="row">
      <div class="col-lg-5 mx-auto coin-info">
        <h2>About</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rutrum quam vitae metus suscipit porta. Donec elementum lacus vel varius cursus. Nullam a mauris efficitur, aliquam felis at, hendrerit ligula. Aenean sodales, urna id porttitor tempor, metus mi fermentum sem, id vehicula turpis nibh eu dui. Integer eu tristique nisi. Proin quis consequat nunc, vestibulum placerat ante. Nullam posuere fringilla arcu, a imperdiet nisl bibendum a.</p>
      </div>
      <div class="col-lg-5 mx-auto coin-info">
        <h2>Links</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rutrum quam vitae metus suscipit porta. Donec elementum lacus vel varius cursus. Nullam a mauris efficitur, aliquam felis at, hendrerit ligula. Aenean sodales, urna id porttitor tempor, metus mi fermentum sem, id vehicula turpis nibh eu dui. Integer eu tristique nisi. Proin quis consequat nunc, vestibulum placerat ante. Nullam posuere fringilla arcu, a imperdiet nisl bibendum a.</p>
      </div>
    </div>
    <br>

  </div>
</section>